spring:
  datasource:
    ##url: jdbc:mariadb://127.0.0.1:3307/blue_networks?useSSL=false&amp;serverTimezone=UTC&amp;autoReconnection=true
    ##url: jdbc:mariadb://211.253.38.156:3306/blue_networks?useSSL=false&amp;serverTimezone=UTC&amp;autoReconnection=true
    url: jdbc:mariadb://192.168.30.120:3306/blue_networks?useSSL=false&amp;serverTimezone=UTC&amp;autoReconnection=true
    username: blue_networks
    password: blue_networks

  aop:
    proxy-target-class: true

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  messages:
    basename: locale/messages
    encoding: UTF-8

devtools:
  livereload:
    enabled: true


mybatis:
  type-aliases-package: com.bluenetworks.webapp.common
  mapper-locations: classpath:mapper/**/*.xml
  


server:
  port: 9070
  servlet:
    session:
      timeout: 180000 # 30분 - 초 설정

    context-path:

logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: trace
  config: classpath:logback-spring.xml


# WEB - WAS Ajp 방화벽 (내장 톰캣 설정 시) - (짐작)
#fwaccess:
#  properties:
#    tomcat_ajp_protocol: AJP/1.3
#    tomcat_ajp_port: 9009
#    tomcat_ajp_redirect_port: 9443
#    tomcat_ajp_address: 0.0.0.0
#    tomcat_ajp_allowed_request_attributes_pattern: .*
    #tomcat_ajp_enable: true



